### ISSUE TITLE
Peer Feedback from Jimmy

### ISSUE THREAD

**Issue by jimmyliu1326** [STAT547-UBC-2019-20/group_2_youtube#37]
Hi Group 2,

Here is my feedback for your project so far:

Positives:
* I really liked your choice of dataset that describes various statistics about Youtube videos
* Your research question and plan of questions are certainly very interesting
* The EDA plots are very informative and show some clear trends between various measured variables, and a very skewed distribution of video types on Youtube
* Three of the five scripts ran successfully without errors via command line and generated the expected outputs
* Sufficient comments were annotated to describe the codes in the scripts

Negatives:
* I wasn’t able to knit your milestone01.Rmd successfully due to incorrect path to input file specified. I had to make minor adjustments to your code to knit it correctly. To ensure that your scripts will work for any users, I would recommend using the `here` R package to consistently set the default working directory as the directory that contains the `.Rproj` file
* The milestone01 doc will look a lot cleaner if you suppress the messages and warnings from the code chunks, as well as not including your code chunks that load the R packages.
* For the tables produced by `kable`, especially the tables with only two columns, it would look a lot more aesthetically pleasing if you add `kableExtra::kable_styling(full_width = F)` to shorten the width of the table which will remove the significant amount of white spaces between your columns in the table
* No `.md` or `.html` versions of milestone01.Rmd are available under `docs/`
* The link to milestone01 report does not work in your `Readme.md`
* Under the usage section, `corrplot` is missing as one of the required R packages
* Copy pasting the first two command lines written in the usage section of `Readme` resulted in errors because the scripts extension `.R` isn’t capitalized.
* For `load_data.R`, the library `glue` isn’t loaded although the function `glue` is called in the script
* The title of the correlation plot is not displayed properly, I would resize the image

Suggestions:
* Include a brief description of what each of your command line does in the `Readme` usage section
* For your EDA plot that shows the correlation between views and likes across different video categories, I would include an error bar for each mean value to illustrate the spread of the data.

Cheers,
Jimmy

**Comment by hanrach** [comment]
Hi Jimmy, 

Thank you for your feedback! We have fixed the following issues that you have suggested:
- We load the data from our data directory. Users must run `make data/youtube_data.csv` and `make data/youtube_processed.csv` before knitting the document.
- We have suppressed the warnings and excluded the code chunk loading in packages.
- We used `kableExtra::kable_styling(full_width = F)` as suggested.
- include `.html` format of the milestone 1 report.
- Fixed the link for milestone 1 report.
- Added `corrplot` package to install in our usage section.
- Fixed the typo in loading and processing data in the usage section (including `.R`).
- Included to `library(glue)` in `load_data.R`.
- Included comments explaining what each command executes.

We delegate resizing the correlation plot and including the error bar for `top10_mean_views_likes.png` due to the lack of time for this milestone!
