### ISSUE TITLE
Peer feedback

### ISSUE THREAD

**Issue by xiaoyuanf** [STAT547-UBC-2019-20/group_2_youtube#43]
Hi Group 2,

Very interesting dataset! The research question is clearly defined, and I look forward to reading your final findings!

The repository is organized in a useful and sensible way. The usage section in the README is clear and helpful. I could run most scripts and reproduce the data and plots. The scripts are also well documented and easy to follow. 

Especially, I like that you added some messages in process_data.R, such as "Reading in data..", "Saving processed data..", so that users can tell what's going on and it's easier to wait.

### Some issues:
- I couldn't run scripts/load_data.R. Seems the [url](https://raw.githubusercontent.com/STAT547-UBC-2019-20/group_2_youtube/master/data/CAvideos.csv) of the data has changed.
- I can't knit milestone1_547.Rmd, because Rstudio can't find CAvideos.csv. I would suggest using `here` package or URL to load the data. 

### Suggestion:
- The plot of mean video views and likes for the top 10 most viewed video categories shows that there may be different relationships between views and likes in different categories. Perhaps a scatter plot of views and likes with categories in different colours, or a box/violin plot of the distribution of views and likes in various categories can give you more information. 

Overall, good job!

**Comment by hanrach** [comment]
Hi @xiaoyuanf,

Thank you for your feedback! We have changed the following based on your suggestions:
- We updated the url link for the data. 
- Since we load the data from our data directory, users must run `make data/youtube_data.csv` and `make data/youtube_processed.csv` before knitting the document. 

Thank you for your detailed suggestion for `top10_mean_views_likes.png` . We will reflect this suggestion later on.
