### ISSUE TITLE
M5 Feedback

### ISSUE THREAD

**Issue by yuliaUU** [STAT547-UBC-2019-20/group_2_youtube#56]
1. Running App: all is great but the message displays:
`Fire started at 0.0.0.0:8050`, and it won't work on my computer,  but if I enter `http://127.0.0.1:8050/`, it works.
I still get a warning `warning: Ignoring unknown aesthetics: label from NULL` while running it

2. I really like the color scheme of the app!
but something is off with the layout: the position of slider and dropdown is very weird. it should not be a center of your app

3. I found no reference to the source dataset  

4. "View counts over time " graph: the nin width maybe is too small?

5. Number of Videos by category:
I have no idea what Category # means on y-axis. The numbers should be explained or labeled in a different way 

6. Trends between Likes/Dislikes graph
May be logging the x-axis scale will improve the readability of the graph?

**Comment by hanrach** [comment]
Hi @yuliaUU, 

Thank you for your feedback!

1. `app$run_server(debug=TRUE)` would not run on my computer, so we used `0.0.0.0` as suggested by Firas in previous lecture. I've added in comments to use `127.0.0.1` in `app.R` so you can comment this out to run. 

2.  Thanks for this suggestion, we've moved the core components to the side.

3.  We've added the source in the app description.

4. We decided not to change this because we want to get a detailed visualization of the counts over the period of time. Also by increasing the width of the bars the graph would become too big and would not fit on the screen.

5. The table (you can scroll on it) was added to describe the category numbers.

6. Done, our plots look much better.
